---
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-debian11-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
verifier:
  name: ansible
#lint: |
#  set -e
#  yamllint --strict --config-file .yamllint .
#  ansible-lint --strict --config-file .ansible-lint
