version: 2.1

orbs:
  terraform: circleci/terraform@3.2.0
  path-filtering: circleci/path-filtering@0.1.3


workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          base-revision: master
          config-path: .circleci/continue-terraform.yml
          mapping: |
            terraform/.* build-code true