version: 2.1

orbs:
  terraform: circleci/terraform@3.2.0

commands:
  setup_terraform_credentials:
    steps:
      - run:
          name: setup terraform credentials
          command: |
            mkdir ~/.terraform.d
            echo "{\"credentials\": { \"app.terraform.io\": {token = \"$TERRAFORM_TOKEN\"}}}" > ~/.terraform.d/credentials.tfrc.json

executors:
  terraform:
    working_directory: ~/repo
    docker:
      - image: hashicorp/terraform:1.3.6

jobs:
  terraform-apply:
    executor: terraform
    steps:
      - restore_cache:
          key: terraform-{{ .Environment.CIRCLE_SHA1 }}
      - setup_terraform_credentials
      - run:
          name: terraform apply
          command: |
            cd terraform
            terraform apply -auto-approve

  terraform-plan:
    executor: terraform
    steps:
      - checkout
      - setup_terraform_credentials
      - run:
          name: terraform plan and notify
          command: |
            ls -l
            cat ~/.terraform.d/credentials.tfrc.json
            terraform init
            terraform plan | ../.circleci/bin/tfnotify plan
      - save_cache:
          key: terraform-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

workflows:
  deploy_infrastructure:
    jobs:
      - terraform-plan:
          context: terraform
      - hold-terraform-apply:
          type: approval
          requires:
            - terraform-plan
      - terraform-apply:
         context: terraform
         requires:
           - terraform-plan
           - hold-terraform-apply
         filters:
           branches:
             only:
               - master