---
- name: apt-get update
  ansible.builtin.apt:
    update_cache: true

- name: install curl
  ansible.builtin.package:
    name: curl
    state: present

- name: install dump-metrics.sh
  ansible.builtin.template:
    src: dump-metrics.sh
    dest: /root/dump-metrics.sh
    owner: root
    group: root
    mode: '744'

- name: install systemd service
  ansible.builtin.template:
    src: systemd-service.j2
    dest: /etc/systemd/system/metrics.service
    owner: root
    group: root
    mode: '0644'
  notify: "systemd reload"

- name: install systemd timer
  ansible.builtin.template:
    src: systemd-timer.j2
    dest: /etc/systemd/system/metrics.timer
    owner: root
    group: root
    mode: '0644'
  notify: "systemd reload"

- name: enable systemd service
  ansible.builtin.systemd:
    state: started
    name: metrics.service
    enabled: true
  notify: "systemd reload"
  changed_when: false

- name: enable systemd timer
  ansible.builtin.systemd:
    state: started
    name: metrics.timer
    enabled: true
  notify: "systemd reload"
  changed_when: false
