---
driver:
  name: podman
platforms:
  - name: instance
    image: ubi8/ubi-init
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/usr/sbin/init"
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
verifier:
  name: ansible
lint: |
  set -e
  yamllint --strict --config-file .yamllint .
#  ansible-lint --strict --config-file .ansible-lint
